# =====================================================================
#  ZombieApocalypse - BOSS : UNDEAD OVERLORD  (Skript 2.9.5)
#  Apparition automatique toutes les {@intervalle} pres d'un joueur au hasard.
#  Commandes: /boss spawn | /boss reset    (permission za.admin)
# =====================================================================

options:
    intervalle: 90 minutes

on load:
    set {za::boss::vivant} to false

function za_boss_spawn():
    if {za::boss::vivant} is true:
        stop
    if size of za_monde_joueurs() is 0:
        stop
    set {_p} to random element out of za_monde_joueurs()
    set {_l} to location of {_p}
    add 28 to x-coordinate of {_l}
    add 10 to z-coordinate of {_l}
    set {_b} to highest block at {_l}
    set {_y} to (y-coordinate of (location of {_b})) + 1
    execute console command "mm mobs spawn ZA_Overlord 1 %world of {_l}%,%floor(x-coordinate of {_l})%,%{_y}%,%floor(z-coordinate of {_l})%"
    set {za::boss::vivant} to true
    za_diffuser("&4&lL'UNDEAD OVERLORD S'EST EVEILLE ! &7Il rode pres de %{_p}%...")

every {@intervalle}:
    za_boss_spawn()

command /boss <text>:
    permission: za.admin
    trigger:
        if arg-1 is "spawn":
            za_boss_spawn()
        else if arg-1 is "reset":
            set {za::boss::vivant} to false
            send "&aEtat du boss reinitialise." to sender
        else:
            send "&cUsage: /boss <spawn|reset>" to sender

# appelee par MythicMobs a la mort de l'Overlord
command /zaboss <text>:
    executable by: console
    trigger:
        if arg-1 is "mort":
            set {za::boss::vivant} to false
            za_diffuser("&a&lL'UNDEAD OVERLORD EST TOMBE !")
            za_chronique_boss()
