# =====================================================================
#  ZombieApocalypse - BATIMENTS SPECIAUX
#  Structures autonomes generees (meme technique que les labos et les camps), avec un vrai plan de pieces et une palette
#  pensee pour chaque theme. Toutes passent par la fonction commune de decor d'abandon a la fin (toiles d'araignee,
#  fissures, taches, trous, lierre), pour que ca ait l'air abandonne depuis des mois, pas neuf. Acces libre (pas de
#  Blood Moon requise, contrairement aux labos scelles) ; le danger et le loot varient selon le theme (l'ecole est faible, la caserne est la plus dure des 8).
#  Admin : /evenement hopital | police | supermarche | station | laboratoire | caserne | ecole | centrale
# =====================================================================

# =====================================================================
#  HOPITAL : accueil, salle des malades (2 lits), pharmacie (loot medical). Danger moyen.
# =====================================================================
function za_batiment_hopital():
    if size of {za::bat::hopital::liste::*} >= 4:
        stop
    if size of za_monde_joueurs() is 0:
        stop
    set {_p} to random element out of za_monde_joueurs()
    set {_g} to za_point_loin({_p}, 50, 90)
    set {_bx} to floor(x-coordinate of {_g})
    set {_gy} to floor(y-coordinate of {_g})
    set {_bz} to floor(z-coordinate of {_g})
    set {_w} to world of {_g}
    set {_wd} to za_dim({_w})
    execute console command "execute in %{_wd}% run fill %{_bx} - 1% %{_gy} + 1% %{_bz} - 1% %{_bx} + 13% %{_gy} + 6% %{_bz} + 9% minecraft:air"
    execute console command "execute in %{_wd}% run fill %{_bx}% %{_gy}% %{_bz}% %{_bx} + 12% %{_gy} + 4% %{_bz} + 8% minecraft:white_concrete hollow"
    execute console command "execute in %{_wd}% run fill %{_bx}% %{_gy} + 5% %{_bz}% %{_bx} + 12% %{_gy} + 5% %{_bz} + 8% minecraft:light_gray_concrete"
    execute console command "execute in %{_wd}% run fill %{_bx} + 1% %{_gy}% %{_bz} + 1% %{_bx} + 4% %{_gy}% %{_bz} + 7% minecraft:light_gray_concrete"
    execute console command "execute in %{_wd}% run fill %{_bx} + 5% %{_gy}% %{_bz} + 1% %{_bx} + 9% %{_gy}% %{_bz} + 7% minecraft:white_concrete"
    execute console command "execute in %{_wd}% run fill %{_bx} + 10% %{_gy}% %{_bz} + 1% %{_bx} + 11% %{_gy}% %{_bz} + 7% minecraft:light_gray_concrete"
    execute console command "execute in %{_wd}% run fill %{_bx} + 7% %{_gy}% %{_bz} + 1% %{_bx} + 7% %{_gy}% %{_bz} + 7% minecraft:red_concrete"
    execute console command "execute in %{_wd}% run fill %{_bx} + 1% %{_gy} + 2% %{_bz}% %{_bx} + 11% %{_gy} + 3% %{_bz}% minecraft:glass_pane"
    execute console command "execute in %{_wd}% run fill %{_bx} + 1% %{_gy} + 1% %{_bz}% %{_bx} + 2% %{_gy} + 3% %{_bz}% minecraft:air"
    execute console command "execute in %{_wd}% run fill %{_bx} + 1% %{_gy} + 2% %{_bz} + 8% %{_bx} + 11% %{_gy} + 3% %{_bz} + 8% minecraft:glass_pane"
    execute console command "execute in %{_wd}% run fill %{_bx} + 1% %{_gy} + 5% %{_bz} - 1% %{_bx} + 1% %{_gy} + 7% %{_bz} - 1% minecraft:red_concrete"
    execute console command "execute in %{_wd}% run fill %{_bx}% %{_gy} + 6% %{_bz} - 1% %{_bx} + 2% %{_gy} + 6% %{_bz} - 1% minecraft:red_concrete"
    execute console command "execute in %{_wd}% run fill %{_bx} + 4% %{_gy}% %{_bz}% %{_bx} + 4% %{_gy} + 4% %{_bz} + 8% minecraft:white_concrete"
    execute console command "execute in %{_wd}% run fill %{_bx} + 4% %{_gy} + 1% %{_bz} + 3% %{_bx} + 4% %{_gy} + 2% %{_bz} + 4% minecraft:air"
    execute console command "execute in %{_wd}% run fill %{_bx} + 9% %{_gy}% %{_bz}% %{_bx} + 9% %{_gy} + 4% %{_bz} + 8% minecraft:light_gray_concrete"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 9% %{_gy} + 1% %{_bz} + 4% minecraft:iron_door[facing=east,half=lower]"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 9% %{_gy} + 2% %{_bz} + 4% minecraft:iron_door[facing=east,half=upper]"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 2% %{_gy} + 4% %{_bz} + 2% minecraft:sea_lantern"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 2% %{_gy} + 4% %{_bz} + 6% minecraft:sea_lantern"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 7% %{_gy} + 4% %{_bz} + 2% minecraft:sea_lantern"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 7% %{_gy} + 4% %{_bz} + 6% minecraft:sea_lantern"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 10% %{_gy} + 4% %{_bz} + 4% minecraft:sea_lantern"
    execute console command "execute in %{_wd}% run fill %{_bx} + 1% %{_gy} + 1% %{_bz} + 1% %{_bx} + 3% %{_gy} + 1% %{_bz} + 1% minecraft:smooth_stone_slab"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 2% %{_gy} + 1% %{_bz} + 1% minecraft:lectern[facing=south]"
    execute console command "execute in %{_wd}% run fill %{_bx} + 1% %{_gy} + 1% %{_bz} + 6% %{_bx} + 1% %{_gy} + 1% %{_bz} + 7% minecraft:oak_stairs[facing=east]"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 6% %{_gy} + 1% %{_bz} + 1% minecraft:white_bed[facing=south,part=head]"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 6% %{_gy} + 1% %{_bz} + 2% minecraft:white_bed[facing=south,part=foot]"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 5% %{_gy} + 1% %{_bz} + 1% minecraft:brewing_stand"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 6% %{_gy} + 1% %{_bz} + 6% minecraft:white_bed[facing=north,part=head]"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 6% %{_gy} + 1% %{_bz} + 5% minecraft:white_bed[facing=north,part=foot]"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 7% %{_gy} + 1% %{_bz} + 6% minecraft:brewing_stand"
    execute console command "execute in %{_wd}% run fill %{_bx} + 10% %{_gy} + 1% %{_bz} + 1% %{_bx} + 11% %{_gy} + 1% %{_bz} + 1% minecraft:smooth_stone_slab"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 10% %{_gy} + 1% %{_bz} + 6% minecraft:chest[facing=south]"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 11% %{_gy} + 1% %{_bz} + 6% minecraft:chest[facing=south]"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 10% %{_gy} + 1% %{_bz} - 1% minecraft:oak_sign[rotation=8]"
    set {_s} to block at location({_bx} + 10, {_gy} + 1, {_bz} - 1, {_w})
    set line 1 of {_s} to "&8Pharmacie"
    set line 2 of {_s} to "&8Reserve fermee"
    za_decay({_wd}, {_bx}, {_gy}, {_bz}, {_bx} + 12, {_gy} + 4, {_bz} + 8, 30)
    set {_c1} to block at location({_bx} + 10, {_gy} + 1, {_bz} + 6, {_w})
    set {_c2} to block at location({_bx} + 11, {_gy} + 1, {_bz} + 6, {_w})
    add za_item("honey bottle", "Antibiotique", "&b", random integer between 2 and 4) to inventory of {_c1}
    add za_item("honey bottle", "Serum", "&d", random integer between 1 and 2) to inventory of {_c1}
    add za_item("paper", "Bandage", "&f", random integer between 4 and 8) to inventory of {_c1}
    add za_item("gold nugget", "Jeton de Survie", "&6", random integer between 8 and 16) to inventory of {_c2}
    if chance of 20%:
        add za_item("leather cap", "Masque a gaz", "&2", 1) to inventory of {_c2}
    za_relique_coffre({_c2})
    execute console command "mm mobs spawn ZA_Shambler 1 %{_w}%,%{_bx} + 6%,%{_gy} + 1%,%{_bz} + 3%"
    execute console command "mm mobs spawn ZA_Shambler 1 %{_w}%,%{_bx} + 2%,%{_gy} + 1%,%{_bz} + 4%"
    execute console command "mm mobs spawn ZA_Screamer 1 %{_w}%,%{_bx} + 6%,%{_gy} + 1%,%{_bz} + 5%"
    add "%{_bx}%_%{_gy}%_%{_bz}%_%{_w}%" to {za::bat::hopital::liste::*}
    set {_ax} to floor({_bx} / 100) * 100
    set {_az} to floor({_bz} / 100) * 100
    za_diffuser("&f[Radio] &7Un hopital abandonne a ete repere vers X=%{_ax}% Z=%{_az}% (+/- 100). Des medicaments, peut-etre... si les malades laissent passer.")
    za_journal("Un hopital abandonne a ete repere.")

# =====================================================================
#  POSTE DE POLICE : accueil, cellule (barreaux), armurerie (armes TaCZ legeres). Danger moyen.
# =====================================================================
function za_batiment_police():
    if size of {za::bat::police::liste::*} >= 4:
        stop
    if size of za_monde_joueurs() is 0:
        stop
    set {_p} to random element out of za_monde_joueurs()
    set {_g} to za_point_loin({_p}, 50, 90)
    set {_bx} to floor(x-coordinate of {_g})
    set {_gy} to floor(y-coordinate of {_g})
    set {_bz} to floor(z-coordinate of {_g})
    set {_w} to world of {_g}
    set {_wd} to za_dim({_w})
    execute console command "execute in %{_wd}% run fill %{_bx} - 1% %{_gy} + 1% %{_bz} - 1% %{_bx} + 11% %{_gy} + 6% %{_bz} + 8% minecraft:air"
    execute console command "execute in %{_wd}% run fill %{_bx}% %{_gy}% %{_bz}% %{_bx} + 10% %{_gy} + 4% %{_bz} + 7% minecraft:light_blue_concrete hollow"
    execute console command "execute in %{_wd}% run fill %{_bx}% %{_gy} + 5% %{_bz}% %{_bx} + 10% %{_gy} + 5% %{_bz} + 7% minecraft:gray_concrete"
    execute console command "execute in %{_wd}% run fill %{_bx} + 1% %{_gy}% %{_bz} + 1% %{_bx} + 9% %{_gy}% %{_bz} + 6% minecraft:gray_concrete"
    execute console command "execute in %{_wd}% run fill %{_bx} + 1% %{_gy} + 2% %{_bz}% %{_bx} + 9% %{_gy} + 3% %{_bz}% minecraft:iron_bars"
    execute console command "execute in %{_wd}% run fill %{_bx} + 1% %{_gy} + 1% %{_bz}% %{_bx} + 2% %{_gy} + 3% %{_bz}% minecraft:air"
    execute console command "execute in %{_wd}% run fill %{_bx} + 1% %{_gy} + 2% %{_bz} + 7% %{_bx} + 9% %{_gy} + 3% %{_bz} + 7% minecraft:iron_bars"
    execute console command "execute in %{_wd}% run fill %{_bx} + 3% %{_gy}% %{_bz}% %{_bx} + 3% %{_gy} + 4% %{_bz} + 7% minecraft:light_blue_concrete"
    execute console command "execute in %{_wd}% run fill %{_bx} + 3% %{_gy} + 1% %{_bz} + 3% %{_bx} + 3% %{_gy} + 2% %{_bz} + 4% minecraft:air"
    execute console command "execute in %{_wd}% run fill %{_bx} + 7% %{_gy}% %{_bz}% %{_bx} + 7% %{_gy} + 4% %{_bz} + 7% minecraft:gray_concrete"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 7% %{_gy} + 1% %{_bz} + 4% minecraft:iron_door[facing=east,half=lower]"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 7% %{_gy} + 2% %{_bz} + 4% minecraft:iron_door[facing=east,half=upper]"
    execute console command "execute in %{_wd}% run fill %{_bx} + 4% %{_gy} + 1% %{_bz} + 1% %{_bx} + 6% %{_gy} + 3% %{_bz} + 6% minecraft:iron_bars hollow"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 5% %{_gy} + 1% %{_bz} + 1% minecraft:iron_door[facing=south,half=lower]"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 5% %{_gy} + 2% %{_bz} + 1% minecraft:iron_door[facing=south,half=upper]"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 1% %{_gy} + 4% %{_bz} + 3% minecraft:sea_lantern"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 9% %{_gy} + 4% %{_bz} + 3% minecraft:sea_lantern"
    execute console command "execute in %{_wd}% run fill %{_bx} + 1% %{_gy} + 1% %{_bz} + 1% %{_bx} + 2% %{_gy} + 1% %{_bz} + 1% minecraft:smooth_stone_slab"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 1% %{_gy} + 1% %{_bz} - 1% minecraft:oak_sign[rotation=8]"
    set {_s} to block at location({_bx} + 1, {_gy} + 1, {_bz} - 1, {_w})
    set line 1 of {_s} to "&9Poste de"
    set line 2 of {_s} to "&9Police"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 8% %{_gy} + 1% %{_bz} + 6% minecraft:chest[facing=south]"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 9% %{_gy} + 1% %{_bz} + 6% minecraft:chest[facing=south]"
    za_decay({_wd}, {_bx}, {_gy}, {_bz}, {_bx} + 10, {_gy} + 3, {_bz} + 7, 22)
    set {_c2} to block at location({_bx} + 9, {_gy} + 1, {_bz} + 6, {_w})
    execute console command "execute in %{_wd}% run item replace block %{_bx} + 8% %{_gy} + 1% %{_bz} + 6% container.0 with tacz:modern_kinetic_gun{GunId:""tacz:glock_17"",GunFireMode:""SEMI""} 1"
    execute console command "execute in %{_wd}% run item replace block %{_bx} + 8% %{_gy} + 1% %{_bz} + 6% container.1 with tacz:ammo{AmmoId:""tacz:9mm""} 30"
    execute console command "execute in %{_wd}% run item replace block %{_bx} + 9% %{_gy} + 1% %{_bz} + 6% container.0 with tacz:attachment{AttachmentId:""tacz:muzzle_silencer_ursus""} 1"
    add za_item("gold nugget", "Jeton de Survie", "&6", random integer between 6 and 12) to inventory of {_c2}
    execute console command "mm mobs spawn ZA_Shambler 1 %{_w}%,%{_bx} + 2%,%{_gy} + 1%,%{_bz} + 3%"
    execute console command "mm mobs spawn ZA_Runner 1 %{_w}%,%{_bx} + 5%,%{_gy} + 1%,%{_bz} + 4%"
    add "%{_bx}%_%{_gy}%_%{_bz}%_%{_w}%" to {za::bat::police::liste::*}
    set {_ax} to floor({_bx} / 100) * 100
    set {_az} to floor({_bz} / 100) * 100
    za_diffuser("&9[Radio] &7Un poste de police abandonne a ete repere vers X=%{_ax}% Z=%{_az}% (+/- 100).")
    za_journal("Un poste de police abandonne a ete repere.")

# =====================================================================
#  SUPERMARCHE : rayons, caisse, reserve (nourriture en quantite). Danger faible.
# =====================================================================
function za_batiment_supermarche():
    if size of {za::bat::super::liste::*} >= 5:
        stop
    if size of za_monde_joueurs() is 0:
        stop
    set {_p} to random element out of za_monde_joueurs()
    set {_g} to za_point_loin({_p}, 40, 80)
    set {_bx} to floor(x-coordinate of {_g})
    set {_gy} to floor(y-coordinate of {_g})
    set {_bz} to floor(z-coordinate of {_g})
    set {_w} to world of {_g}
    set {_wd} to za_dim({_w})
    execute console command "execute in %{_wd}% run fill %{_bx} - 1% %{_gy} + 1% %{_bz} - 1% %{_bx} + 15% %{_gy} + 6% %{_bz} + 9% minecraft:air"
    execute console command "execute in %{_wd}% run fill %{_bx}% %{_gy}% %{_bz}% %{_bx} + 14% %{_gy} + 4% %{_bz} + 8% minecraft:white_concrete hollow"
    execute console command "execute in %{_wd}% run fill %{_bx}% %{_gy} + 5% %{_bz}% %{_bx} + 14% %{_gy} + 5% %{_bz} + 8% minecraft:light_gray_concrete"
    execute console command "execute in %{_wd}% run fill %{_bx} + 1% %{_gy}% %{_bz} + 1% %{_bx} + 13% %{_gy}% %{_bz} + 7% minecraft:light_gray_concrete"
    execute console command "execute in %{_wd}% run fill %{_bx} + 2% %{_gy} + 2% %{_bz}% %{_bx} + 12% %{_gy} + 3% %{_bz}% minecraft:glass_pane"
    execute console command "execute in %{_wd}% run fill %{_bx} + 6% %{_gy} + 1% %{_bz}% %{_bx} + 8% %{_gy} + 3% %{_bz}% minecraft:air"
    execute console command "execute in %{_wd}% run fill %{_bx} + 2% %{_gy} + 1% %{_bz} + 1% %{_bx} + 2% %{_gy} + 2% %{_bz} + 6% minecraft:bookshelf"
    execute console command "execute in %{_wd}% run fill %{_bx} + 2% %{_gy} + 1% %{_bz} + 1% %{_bx} + 2% %{_gy} + 1% %{_bz} + 6% minecraft:yellow_concrete replace bookshelf"
    execute console command "execute in %{_wd}% run fill %{_bx} + 6% %{_gy} + 1% %{_bz} + 1% %{_bx} + 6% %{_gy} + 2% %{_bz} + 6% minecraft:bookshelf"
    execute console command "execute in %{_wd}% run fill %{_bx} + 6% %{_gy} + 1% %{_bz} + 1% %{_bx} + 6% %{_gy} + 1% %{_bz} + 6% minecraft:red_concrete replace bookshelf"
    execute console command "execute in %{_wd}% run fill %{_bx} + 10% %{_gy} + 1% %{_bz} + 1% %{_bx} + 10% %{_gy} + 2% %{_bz} + 6% minecraft:bookshelf"
    execute console command "execute in %{_wd}% run fill %{_bx} + 10% %{_gy} + 1% %{_bz} + 1% %{_bx} + 10% %{_gy} + 1% %{_bz} + 6% minecraft:blue_concrete replace bookshelf"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 1% %{_gy} + 4% %{_bz} + 4% minecraft:sea_lantern"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 6% %{_gy} + 4% %{_bz} + 4% minecraft:sea_lantern"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 11% %{_gy} + 4% %{_bz} + 4% minecraft:sea_lantern"
    execute console command "execute in %{_wd}% run fill %{_bx} + 1% %{_gy} + 1% %{_bz} + 1% %{_bx} + 1% %{_gy} + 1% %{_bz} + 2% minecraft:smooth_stone_slab"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 1% %{_gy} + 1% %{_bz}% minecraft:composter"
    execute console command "execute in %{_wd}% run fill %{_bx} + 13% %{_gy}% %{_bz}% %{_bx} + 13% %{_gy} + 4% %{_bz} + 8% minecraft:light_gray_concrete"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 14% %{_gy} + 1% %{_bz} + 6% minecraft:chest[facing=south]"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 14% %{_gy} + 1% %{_bz} + 5% minecraft:barrel[facing=up]"
    za_decay({_wd}, {_bx}, {_gy}, {_bz}, {_bx} + 14, {_gy} + 3, {_bz} + 8, 26)
    set {_c1} to block at location({_bx} + 14, {_gy} + 1, {_bz} + 6, {_w})
    set {_c2} to block at location({_bx} + 14, {_gy} + 1, {_bz} + 5, {_w})
    add za_item("bread", "Conserve", "&f", random integer between 4 and 8) to inventory of {_c1}
    add za_item("apple", "Pomme", "&a", random integer between 2 and 5) to inventory of {_c1}
    add za_item("glass bottle", "Eau en bouteille", "&b", random integer between 2 and 4) to inventory of {_c2}
    add za_item("gold nugget", "Jeton de Survie", "&6", random integer between 3 and 8) to inventory of {_c2}
    execute console command "mm mobs spawn ZA_Shambler 1 %{_w}%,%{_bx} + 4%,%{_gy} + 1%,%{_bz} + 4%"
    execute console command "mm mobs spawn ZA_Shambler 1 %{_w}%,%{_bx} + 8%,%{_gy} + 1%,%{_bz} + 4%"
    execute console command "mm mobs spawn ZA_Bloater 1 %{_w}%,%{_bx} + 12%,%{_gy} + 1%,%{_bz} + 4%"
    add "%{_bx}%_%{_gy}%_%{_bz}%_%{_w}%" to {za::bat::super::liste::*}
    set {_ax} to floor({_bx} / 80) * 80
    set {_az} to floor({_bz} / 80) * 80
    za_diffuser("&e[Radio] &7Un supermarche a moitie pille a ete repere vers X=%{_ax}% Z=%{_az}% (+/- 80).")
    za_journal("Un supermarche a ete repere.")

# =====================================================================
#  STATION-SERVICE : petite, deux pompes exterieures, loot mecanique. Danger faible.
# =====================================================================
function za_batiment_station():
    if size of {za::bat::station::liste::*} >= 5:
        stop
    if size of za_monde_joueurs() is 0:
        stop
    set {_p} to random element out of za_monde_joueurs()
    set {_g} to za_point_loin({_p}, 40, 80)
    set {_bx} to floor(x-coordinate of {_g})
    set {_gy} to floor(y-coordinate of {_g})
    set {_bz} to floor(z-coordinate of {_g})
    set {_w} to world of {_g}
    set {_wd} to za_dim({_w})
    execute console command "execute in %{_wd}% run fill %{_bx} - 3% %{_gy} + 1% %{_bz} - 1% %{_bx} + 9% %{_gy} + 6% %{_bz} + 7% minecraft:air"
    execute console command "execute in %{_wd}% run fill %{_bx}% %{_gy}% %{_bz}% %{_bx} + 8% %{_gy} + 4% %{_bz} + 6% minecraft:white_concrete hollow"
    execute console command "execute in %{_wd}% run fill %{_bx}% %{_gy}% %{_bz}% %{_bx} + 8% %{_gy}% %{_bz} + 6% minecraft:light_gray_concrete"
    execute console command "execute in %{_wd}% run fill %{_bx}% %{_gy} + 3% %{_bz}% %{_bx} + 8% %{_gy} + 3% %{_bz}% minecraft:red_concrete"
    execute console command "execute in %{_wd}% run fill %{_bx}% %{_gy} + 1% %{_bz} + 2% %{_bx}% %{_gy} + 3% %{_bz} + 3% minecraft:air"
    execute console command "execute in %{_wd}% run fill %{_bx}% %{_gy} + 5% %{_bz}% %{_bx} + 8% %{_gy} + 5% %{_bz} + 6% minecraft:red_concrete"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 3% %{_gy} + 1% %{_bz} - 1% minecraft:oak_sign[rotation=8]"
    set {_s} to block at location({_bx} + 3, {_gy} + 1, {_bz} - 1, {_w})
    set line 1 of {_s} to "&cStation"
    set line 2 of {_s} to "&cService"
    execute console command "execute in %{_wd}% run fill %{_bx} - 2% %{_gy} + 1% %{_bz} + 2% %{_bx} - 2% %{_gy} + 3% %{_bz} + 2% minecraft:quartz_block"
    execute console command "execute in %{_wd}% run setblock %{_bx} - 2% %{_gy} + 4% %{_bz} + 2% minecraft:lever[face=floor]"
    execute console command "execute in %{_wd}% run fill %{_bx} - 2% %{_gy} + 1% %{_bz} + 4% %{_bx} - 2% %{_gy} + 3% %{_bz} + 4% minecraft:quartz_block"
    execute console command "execute in %{_wd}% run setblock %{_bx} - 2% %{_gy} + 4% %{_bz} + 4% minecraft:lever[face=floor]"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 2% %{_gy} + 4% %{_bz} + 3% minecraft:sea_lantern"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 6% %{_gy} + 4% %{_bz} + 3% minecraft:sea_lantern"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 6% %{_gy} + 1% %{_bz} + 5% minecraft:chest[facing=west]"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 6% %{_gy} + 1% %{_bz} + 1% minecraft:barrel[facing=up]"
    za_decay({_wd}, {_bx}, {_gy}, {_bz}, {_bx} + 8, {_gy} + 3, {_bz} + 6, 18)
    set {_c1} to block at location({_bx} + 6, {_gy} + 1, {_bz} + 5, {_w})
    set {_c2} to block at location({_bx} + 6, {_gy} + 1, {_bz} + 1, {_w})
    add za_item("iron nugget", "Piece mecanique", "&7", random integer between 3 and 6) to inventory of {_c1}
    add za_item("gold nugget", "Jeton de Survie", "&6", random integer between 4 and 10) to inventory of {_c1}
    if chance of 30%:
        add za_item("iron nugget", "Munitions 9 mm", "&7", 15) to inventory of {_c2}
    execute console command "mm mobs spawn ZA_Shambler 1 %{_w}%,%{_bx} + 4%,%{_gy} + 1%,%{_bz} + 3%"
    execute console command "mm mobs spawn ZA_Shambler 1 %{_w}%,%{_bx} - 1%,%{_gy} + 1%,%{_bz} + 3%"
    add "%{_bx}%_%{_gy}%_%{_bz}%_%{_w}%" to {za::bat::station::liste::*}
    set {_ax} to floor({_bx} / 80) * 80
    set {_az} to floor({_bz} / 80) * 80
    za_diffuser("&c[Radio] &7Une station-service a ete reperee vers X=%{_ax}% Z=%{_az}% (+/- 80).")
    za_journal("Une station-service a ete reperee.")

# =====================================================================
#  LABORATOIRE OUVERT : different des labos scelles (Blood Moon) - accessible librement, recherche/infection. Danger moyen.
# =====================================================================
function za_batiment_laboratoire():
    if size of {za::bat::labo2::liste::*} >= 4:
        stop
    if size of za_monde_joueurs() is 0:
        stop
    set {_p} to random element out of za_monde_joueurs()
    set {_g} to za_point_loin({_p}, 50, 90)
    set {_bx} to floor(x-coordinate of {_g})
    set {_gy} to floor(y-coordinate of {_g})
    set {_bz} to floor(z-coordinate of {_g})
    set {_w} to world of {_g}
    set {_wd} to za_dim({_w})
    execute console command "execute in %{_wd}% run fill %{_bx} - 1% %{_gy} + 1% %{_bz} - 1% %{_bx} + 11% %{_gy} + 6% %{_bz} + 9% minecraft:air"
    execute console command "execute in %{_wd}% run fill %{_bx}% %{_gy}% %{_bz}% %{_bx} + 10% %{_gy} + 4% %{_bz} + 8% minecraft:white_concrete hollow"
    execute console command "execute in %{_wd}% run fill %{_bx}% %{_gy} + 5% %{_bz}% %{_bx} + 10% %{_gy} + 5% %{_bz} + 8% minecraft:lime_concrete"
    execute console command "execute in %{_wd}% run fill %{_bx} + 1% %{_gy}% %{_bz} + 1% %{_bx} + 9% %{_gy}% %{_bz} + 7% minecraft:light_gray_concrete"
    execute console command "execute in %{_wd}% run fill %{_bx} + 1% %{_gy} + 1% %{_bz}% %{_bx} + 2% %{_gy} + 3% %{_bz}% minecraft:air"
    execute console command "execute in %{_wd}% run fill %{_bx} + 4% %{_gy}% %{_bz}% %{_bx} + 4% %{_gy} + 4% %{_bz} + 8% minecraft:glass_pane"
    execute console command "execute in %{_wd}% run fill %{_bx} + 4% %{_gy} + 1% %{_bz} + 3% %{_bx} + 4% %{_gy} + 2% %{_bz} + 4% minecraft:air"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 2% %{_gy} + 4% %{_bz} + 4% minecraft:sea_lantern"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 7% %{_gy} + 4% %{_bz} + 2% minecraft:sea_lantern"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 7% %{_gy} + 4% %{_bz} + 6% minecraft:sea_lantern"
    execute console command "execute in %{_wd}% run fill %{_bx} + 6% %{_gy} + 1% %{_bz} + 1% %{_bx} + 6% %{_gy} + 1% %{_bz} + 7% minecraft:brewing_stand"
    execute console command "execute in %{_wd}% run fill %{_bx} + 8% %{_gy} + 1% %{_bz} + 1% %{_bx} + 8% %{_gy} + 1% %{_bz} + 7% minecraft:cauldron"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 1% %{_gy} + 1% %{_bz} + 4% minecraft:lectern[facing=east]"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 9% %{_gy} + 1% %{_bz} + 4% minecraft:chest[facing=west]"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 9% %{_gy} + 1% %{_bz} + 2% minecraft:chest[facing=west]"
    za_decay({_wd}, {_bx}, {_gy}, {_bz}, {_bx} + 10, {_gy} + 3, {_bz} + 8, 24)
    set {_c1} to block at location({_bx} + 9, {_gy} + 1, {_bz} + 4, {_w})
    set {_c2} to block at location({_bx} + 9, {_gy} + 1, {_bz} + 2, {_w})
    add za_item("honey bottle", "Serum", "&d", random integer between 1 and 3) to inventory of {_c1}
    add za_item("honey bottle", "Antibiotique", "&b", random integer between 1 and 2) to inventory of {_c1}
    set {_note} to za_item("paper", "Note de recherche", "&a", 1)
    set lore of {_note} to "Souche instable. Le sujet 4 a montre une resistance inattendue avant de muter."
    add {_note} to inventory of {_c2}
    if chance of 25%:
        add za_item("paper", "Carte d'acces", "&b", 1) to inventory of {_c2}
    za_relique_coffre({_c2})
    execute console command "mm mobs spawn ZA_Shambler 1 %{_w}%,%{_bx} + 6%,%{_gy} + 1%,%{_bz} + 4%"
    execute console command "mm mobs spawn ZA_Observer 1 %{_w}%,%{_bx} + 2%,%{_gy} + 1%,%{_bz} + 4%"
    add "%{_bx}%_%{_gy}%_%{_bz}%_%{_w}%" to {za::bat::labo2::liste::*}
    set {_ax} to floor({_bx} / 100) * 100
    set {_az} to floor({_bz} / 100) * 100
    za_diffuser("&a[Radio] &7Un laboratoire de recherche ouvert a ete repere vers X=%{_ax}% Z=%{_az}% (+/- 100).")
    za_journal("Un laboratoire de recherche ouvert a ete repere.")

# =====================================================================
#  CASERNE MILITAIRE : la plus dure des 8. Baraquement, armurerie lourde (TaCZ militaire), mirador. Danger eleve.
# =====================================================================
function za_batiment_caserne():
    if size of {za::bat::caserne::liste::*} >= 3:
        stop
    if size of za_monde_joueurs() is 0:
        stop
    set {_p} to random element out of za_monde_joueurs()
    set {_g} to za_point_loin({_p}, 60, 100)
    set {_bx} to floor(x-coordinate of {_g})
    set {_gy} to floor(y-coordinate of {_g})
    set {_bz} to floor(z-coordinate of {_g})
    set {_w} to world of {_g}
    set {_wd} to za_dim({_w})
    execute console command "execute in %{_wd}% run fill %{_bx} - 1% %{_gy} + 1% %{_bz} - 1% %{_bx} + 13% %{_gy} + 7% %{_bz} + 9% minecraft:air"
    execute console command "execute in %{_wd}% run fill %{_bx}% %{_gy}% %{_bz}% %{_bx} + 12% %{_gy} + 5% %{_bz} + 8% minecraft:gray_concrete hollow"
    execute console command "execute in %{_wd}% run fill %{_bx}% %{_gy} + 6% %{_bz}% %{_bx} + 12% %{_gy} + 6% %{_bz} + 8% minecraft:green_concrete"
    execute console command "execute in %{_wd}% run fill %{_bx} + 1% %{_gy}% %{_bz} + 1% %{_bx} + 11% %{_gy}% %{_bz} + 7% minecraft:gray_concrete"
    execute console command "execute in %{_wd}% run fill %{_bx} + 2% %{_gy} + 1% %{_bz}% %{_bx} + 3% %{_gy} + 3% %{_bz}% minecraft:air"
    execute console command "execute in %{_wd}% run fill %{_bx} + 6% %{_gy}% %{_bz}% %{_bx} + 6% %{_gy} + 5% %{_bz} + 8% minecraft:gray_concrete"
    execute console command "execute in %{_wd}% run fill %{_bx} + 6% %{_gy} + 1% %{_bz} + 3% %{_bx} + 6% %{_gy} + 2% %{_bz} + 4% minecraft:air"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 6% %{_gy} + 1% %{_bz} + 4% minecraft:iron_door[facing=east,half=lower]"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 6% %{_gy} + 2% %{_bz} + 4% minecraft:iron_door[facing=east,half=upper]"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 2% %{_gy} + 5% %{_bz} + 4% minecraft:sea_lantern"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 9% %{_gy} + 5% %{_bz} + 4% minecraft:sea_lantern"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 1% %{_gy} + 1% %{_bz} + 1% minecraft:white_bed[facing=south,part=head]"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 1% %{_gy} + 1% %{_bz} + 2% minecraft:white_bed[facing=south,part=foot]"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 3% %{_gy} + 1% %{_bz} + 1% minecraft:white_bed[facing=south,part=head]"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 3% %{_gy} + 1% %{_bz} + 2% minecraft:white_bed[facing=south,part=foot]"
    execute console command "execute in %{_wd}% run fill %{_bx} + 1% %{_gy} + 1% %{_bz} + 6% %{_bx} + 5% %{_gy} + 3% %{_bz} + 6% minecraft:iron_trapdoor[facing=north,open=false]"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 9% %{_gy} + 1% %{_bz} + 6% minecraft:chest[facing=south]"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 10% %{_gy} + 1% %{_bz} + 6% minecraft:chest[facing=south]"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 11% %{_gy} + 1% %{_bz} + 6% minecraft:chest[facing=south]"
    execute console command "execute in %{_wd}% run fill %{_bx} + 12% %{_gy} + 5% %{_bz} + 3% %{_bx} + 12% %{_gy} + 8% %{_bz} + 3% minecraft:oak_fence"
    execute console command "execute in %{_wd}% run fill %{_bx} + 11% %{_gy} + 8% %{_bz} + 2% %{_bx} + 13% %{_gy} + 8% %{_bz} + 4% minecraft:gray_concrete"
    za_decay({_wd}, {_bx}, {_gy}, {_bz}, {_bx} + 12, {_gy} + 4, {_bz} + 8, 30)
    set {_c1} to block at location({_bx} + 9, {_gy} + 1, {_bz} + 6, {_w})
    set {_c2} to block at location({_bx} + 10, {_gy} + 1, {_bz} + 6, {_w})
    set {_c3} to block at location({_bx} + 11, {_gy} + 1, {_bz} + 6, {_w})
    execute console command "execute in %{_wd}% run item replace block %{_bx} + 9% %{_gy} + 1% %{_bz} + 6% container.0 with tacz:modern_kinetic_gun{GunId:""tacz:ak47"",GunFireMode:""AUTO""} 1"
    execute console command "execute in %{_wd}% run item replace block %{_bx} + 10% %{_gy} + 1% %{_bz} + 6% container.0 with tacz:modern_kinetic_gun{GunId:""tacz:m700"",GunFireMode:""SEMI""} 1"
    execute console command "execute in %{_wd}% run item replace block %{_bx} + 9% %{_gy} + 1% %{_bz} + 6% container.1 with tacz:ammo{AmmoId:""tacz:762x39""} 60"
    execute console command "execute in %{_wd}% run item replace block %{_bx} + 10% %{_gy} + 1% %{_bz} + 6% container.1 with tacz:ammo{AmmoId:""tacz:30_06""} 20"
    add za_item("gold nugget", "Jeton de Survie", "&6", random integer between 15 and 25) to inventory of {_c3}
    za_relique_coffre({_c3})
    execute console command "mm mobs spawn ZA_Brute 1 %{_w}%,%{_bx} + 6%,%{_gy} + 1%,%{_bz} + 5%"
    execute console command "mm mobs spawn ZA_Armored 1 %{_w}%,%{_bx} + 9%,%{_gy} + 1%,%{_bz} + 3%"
    execute console command "mm mobs spawn ZA_Shambler 1 %{_w}%,%{_bx} + 2%,%{_gy} + 1%,%{_bz} + 3%"
    execute console command "mm mobs spawn ZA_Shambler 1 %{_w}%,%{_bx} + 3%,%{_gy} + 1%,%{_bz} + 5%"
    add "%{_bx}%_%{_gy}%_%{_bz}%_%{_w}%" to {za::bat::caserne::liste::*}
    set {_ax} to floor({_bx} / 100) * 100
    set {_az} to floor({_bz} / 100) * 100
    za_diffuser("&2&l[Radio militaire] &7Une caserne a ete reperee vers X=%{_ax}% Z=%{_az}% (+/- 100). Fortement gardee. Venez nombreux.")
    za_journal("Une caserne militaire a ete reperee.")

# =====================================================================
#  ECOLE : loot faible, beaucoup de lore. Danger faible, mais lourd d'ambiance.
# =====================================================================
function za_batiment_ecole():
    if size of {za::bat::ecole::liste::*} >= 4:
        stop
    if size of za_monde_joueurs() is 0:
        stop
    set {_p} to random element out of za_monde_joueurs()
    set {_g} to za_point_loin({_p}, 40, 80)
    set {_bx} to floor(x-coordinate of {_g})
    set {_gy} to floor(y-coordinate of {_g})
    set {_bz} to floor(z-coordinate of {_g})
    set {_w} to world of {_g}
    set {_wd} to za_dim({_w})
    execute console command "execute in %{_wd}% run fill %{_bx} - 1% %{_gy} + 1% %{_bz} - 1% %{_bx} + 11% %{_gy} + 6% %{_bz} + 9% minecraft:air"
    execute console command "execute in %{_wd}% run fill %{_bx}% %{_gy}% %{_bz}% %{_bx} + 10% %{_gy} + 4% %{_bz} + 8% minecraft:orange_concrete hollow"
    execute console command "execute in %{_wd}% run fill %{_bx}% %{_gy} + 5% %{_bz}% %{_bx} + 10% %{_gy} + 5% %{_bz} + 8% minecraft:yellow_concrete"
    execute console command "execute in %{_wd}% run fill %{_bx} + 1% %{_gy}% %{_bz} + 1% %{_bx} + 9% %{_gy}% %{_bz} + 7% minecraft:light_gray_concrete"
    execute console command "execute in %{_wd}% run fill %{_bx} + 1% %{_gy} + 2% %{_bz}% %{_bx} + 9% %{_gy} + 3% %{_bz}% minecraft:glass_pane"
    execute console command "execute in %{_wd}% run fill %{_bx} + 4% %{_gy} + 1% %{_bz}% %{_bx} + 5% %{_gy} + 3% %{_bz}% minecraft:air"
    execute console command "execute in %{_wd}% run fill %{_bx} + 1% %{_gy} + 1% %{_bz} + 6% %{_bx} + 4% %{_gy} + 2% %{_bz} + 6% minecraft:black_concrete"
    execute console command "execute in %{_wd}% run fill %{_bx} + 1% %{_gy} + 1% %{_bz} + 1% %{_bx} + 1% %{_gy} + 1% %{_bz} + 4% minecraft:oak_fence"
    execute console command "execute in %{_wd}% run fill %{_bx} + 1% %{_gy} + 2% %{_bz} + 1% %{_bx} + 1% %{_gy} + 2% %{_bz} + 4% minecraft:oak_pressure_plate"
    execute console command "execute in %{_wd}% run fill %{_bx} + 4% %{_gy} + 1% %{_bz} + 1% %{_bx} + 4% %{_gy} + 1% %{_bz} + 4% minecraft:oak_fence"
    execute console command "execute in %{_wd}% run fill %{_bx} + 4% %{_gy} + 2% %{_bz} + 1% %{_bx} + 4% %{_gy} + 2% %{_bz} + 4% minecraft:oak_pressure_plate"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 2% %{_gy} + 4% %{_bz} + 4% minecraft:sea_lantern"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 8% %{_gy} + 4% %{_bz} + 4% minecraft:sea_lantern"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 7% %{_gy} + 1% %{_bz} + 6% minecraft:chest[facing=south]"
    za_decay({_wd}, {_bx}, {_gy}, {_bz}, {_bx} + 10, {_gy} + 3, {_bz} + 8, 26)
    set {_c1} to block at location({_bx} + 7, {_gy} + 1, {_bz} + 6, {_w})
    add za_item("bread", "Pain rassis", "&f", random integer between 1 and 3) to inventory of {_c1}
    add za_item("gold nugget", "Jeton de Survie", "&6", random integer between 1 and 4) to inventory of {_c1}
    set {_txt::*} to "Devoir inacheve. Personne n'est venu le corriger.", "Ils ont dit que l'ecole etait un abri. Ils avaient tort.", "Madame Roy n'a jamais fini l'appel du jour 12.", "Dessin d'enfant : une maison, un soleil, et un mot barre plusieurs fois."
    loop 3 times:
        set {_note} to za_item("paper", "Cahier oublie", "&f", 1)
        set lore of {_note} to random element out of {_txt::*}
        add {_note} to inventory of {_c1}
    execute console command "mm mobs spawn ZA_Shambler 1 %{_w}%,%{_bx} + 5%,%{_gy} + 1%,%{_bz} + 3%"
    execute console command "mm mobs spawn ZA_Child 1 %{_w}%,%{_bx} + 3%,%{_gy} + 1%,%{_bz} + 5%"
    add "%{_bx}%_%{_gy}%_%{_bz}%_%{_w}%" to {za::bat::ecole::liste::*}
    za_journal("Une ecole abandonnee a ete reperee.")

# =====================================================================
#  CENTRALE ELECTRIQUE : machines, bruit qui attire les morts tant qu'elle tourne. Danger moyen-eleve.
# =====================================================================
function za_batiment_centrale():
    if size of {za::bat::centrale::liste::*} >= 3:
        stop
    if size of za_monde_joueurs() is 0:
        stop
    set {_p} to random element out of za_monde_joueurs()
    set {_g} to za_point_loin({_p}, 50, 90)
    set {_bx} to floor(x-coordinate of {_g})
    set {_gy} to floor(y-coordinate of {_g})
    set {_bz} to floor(z-coordinate of {_g})
    set {_w} to world of {_g}
    set {_wd} to za_dim({_w})
    execute console command "execute in %{_wd}% run fill %{_bx} - 1% %{_gy} + 1% %{_bz} - 1% %{_bx} + 11% %{_gy} + 7% %{_bz} + 9% minecraft:air"
    execute console command "execute in %{_wd}% run fill %{_bx}% %{_gy}% %{_bz}% %{_bx} + 10% %{_gy} + 5% %{_bz} + 8% minecraft:gray_concrete hollow"
    execute console command "execute in %{_wd}% run fill %{_bx}% %{_gy} + 6% %{_bz}% %{_bx} + 10% %{_gy} + 6% %{_bz} + 8% minecraft:gray_concrete"
    execute console command "execute in %{_wd}% run fill %{_bx} + 1% %{_gy}% %{_bz} + 1% %{_bx} + 9% %{_gy}% %{_bz} + 7% minecraft:light_gray_concrete"
    execute console command "execute in %{_wd}% run fill %{_bx} + 4% %{_gy} + 1% %{_bz}% %{_bx} + 5% %{_gy} + 3% %{_bz}% minecraft:air"
    execute console command "execute in %{_wd}% run fill %{_bx} + 2% %{_gy}% %{_bz} + 2% %{_bx} + 2% %{_gy} + 4% %{_bz} + 2% minecraft:redstone_block"
    execute console command "execute in %{_wd}% run fill %{_bx} + 5% %{_gy}% %{_bz} + 2% %{_bx} + 5% %{_gy} + 4% %{_bz} + 2% minecraft:redstone_block"
    execute console command "execute in %{_wd}% run fill %{_bx} + 8% %{_gy}% %{_bz} + 2% %{_bx} + 8% %{_gy} + 4% %{_bz} + 2% minecraft:redstone_block"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 2% %{_gy} + 1% %{_bz} + 5% minecraft:blast_furnace[facing=south]"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 5% %{_gy} + 1% %{_bz} + 5% minecraft:blast_furnace[facing=south]"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 8% %{_gy} + 1% %{_bz} + 5% minecraft:blast_furnace[facing=south]"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 1% %{_gy} + 4% %{_bz} + 4% minecraft:redstone_lamp"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 9% %{_gy} + 4% %{_bz} + 4% minecraft:redstone_lamp"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 5% %{_gy} + 1% %{_bz} + 7% minecraft:lectern[facing=north]"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 4% %{_gy} + 1% %{_bz} + 7% minecraft:lever[face=wall,facing=south]"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 6% %{_gy} + 1% %{_bz} + 7% minecraft:lever[face=wall,facing=south]"
    execute console command "execute in %{_wd}% run setblock %{_bx} + 9% %{_gy} + 1% %{_bz} + 1% minecraft:chest[facing=south]"
    za_decay({_wd}, {_bx}, {_gy}, {_bz}, {_bx} + 10, {_gy} + 4, {_bz} + 8, 28)
    set {_c1} to block at location({_bx} + 9, {_gy} + 1, {_bz} + 1, {_w})
    add za_item("iron nugget", "Piece mecanique", "&7", random integer between 4 and 8) to inventory of {_c1}
    add za_item("gold nugget", "Jeton de Survie", "&6", random integer between 8 and 15) to inventory of {_c1}
    if chance of 20%:
        add za_item("paper", "Carte d'acces", "&b", 1) to inventory of {_c1}
    execute console command "mm mobs spawn ZA_Shambler 1 %{_w}%,%{_bx} + 3%,%{_gy} + 1%,%{_bz} + 4%"
    execute console command "mm mobs spawn ZA_Shambler 1 %{_w}%,%{_bx} + 7%,%{_gy} + 1%,%{_bz} + 4%"
    execute console command "mm mobs spawn ZA_Runner 1 %{_w}%,%{_bx} + 5%,%{_gy} + 1%,%{_bz} + 4%"
    add "%{_bx}%_%{_gy}%_%{_bz}%_%{_w}%" to {za::bat::centrale::liste::*}
    set {za::bat::centrale::pos::%size of {za::bat::centrale::liste::*}%} to location({_bx} + 5, {_gy} + 1, {_bz} + 4, {_w})
    set {_ax} to floor({_bx} / 100) * 100
    set {_az} to floor({_bz} / 100) * 100
    za_diffuser("&6[Radio] &7Une centrale electrique tourne encore vers X=%{_ax}% Z=%{_az}% (+/- 100). Ca fait du bruit. Ca attire du monde.")
    za_journal("Une centrale electrique encore active a ete reperee.")

# tant qu'une centrale tourne, elle fait du bruit et attire des morts (meme principe que les usines Create/IE)
every 60 seconds:
    loop {za::bat::centrale::liste::*}:
        set {_i} to loop-index
        set {_l} to {za::bat::centrale::pos::%{_i}%}
        if {_l} is set:
            if block at {_l} is not air:
                if chance of 35%:
                    za_spawn_at({_l}, "ZA_Shambler", 20, 35)

# =====================================================================
#  DECLENCHEURS PERIODIQUES (l'admin peut forcer chaque type avec /evenement <nom>)
# =====================================================================
every 4 hours:
    if size of za_monde_joueurs() is greater than 0:
        if chance of 40%:
            za_batiment_hopital()

every 5 hours:
    if size of za_monde_joueurs() is greater than 0:
        if chance of 35%:
            za_batiment_police()

every 3 hours:
    if size of za_monde_joueurs() is greater than 0:
        if chance of 45%:
            za_batiment_supermarche()

every 3 hours:
    if size of za_monde_joueurs() is greater than 0:
        if chance of 45%:
            za_batiment_station()

every 5 hours:
    if size of za_monde_joueurs() is greater than 0:
        if chance of 30%:
            za_batiment_laboratoire()

every 6 hours:
    if size of za_monde_joueurs() is greater than 0:
        if chance of 25%:
            za_batiment_caserne()

every 4 hours:
    if size of za_monde_joueurs() is greater than 0:
        if chance of 40%:
            za_batiment_ecole()

every 5 hours:
    if size of za_monde_joueurs() is greater than 0:
        if chance of 30%:
            za_batiment_centrale()
